[book]
authors = ["sh-koh"]
language = "fr"
multilingual = false
src = "src"
title = "Mes notes"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/sh-koh/notes-pro"
git-repository-icon = "fa-github"
no-section-label = true

[output.html.fold]
enable = true
level = 0
