#baseURL = 'https://example.org/'
#languageCode = 'fr-FR'
#title = 'Notes personnelles'
#theme = 'techdoc'

baseURL = "https://example.com"

languageCode = "fr-FR"
DefaultContentLanguage = "fr"
title = "Mes notes personnelles"
theme = "techdoc"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Mes notes"
    #images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = "#9ba0b5"
    custom_background_color = "#161821"
    custom_panel_background_color = "#292d3d"

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    #[[menu.main]]
    #    name = "Sommaire"
    #    url = "/"
    #    weight = 1
    #    identifier = 'sommaire'

    #[[menu.main]]
    #    name = "Base des réseaux"
    #    url = "/docs/networks"
    #    weight = 2
    #    identifier = 'networks'

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
